In [5]:
###------NYC TOTAL POPULATION BY BOROUGH : DATA CLEANING-----###

In [6]:
#Import Packages
import pandas as pd
from Data_Utility import getCurrentDirectory, readCsvFile

In [7]:
#Get Current Working Directory
listDir = getCurrentDirectory()
listDir

['.git',
 '.gitignore',
 'Apriori Association',
 'Data',
 'LICENSE',
 'Python Notebook']

In [8]:
## Read CSV
total_pop = readCsvFile('../Data/Population_by_Borough_NYC.csv')
total_pop.head()

,Age Group,Borough,1950,1950 - Boro share of NYC total,1960,1960 - Boro share of NYC total,1970,1970 - Boro share of NYC total,1980,1980 - Boro share of NYC total,...,2000,2000 - Boro share of NYC total,2010,2010 - Boro share of NYC total,2020,2020 - Boro share of NYC total,2030,2030 - Boro share of NYC total,2040,2040 - Boro share of NYC total
0,Total Population,NYC Total,"7,891,957",100%,"7,781,984",100%,"7,894,862",100%,"7,071,639",100%,...,"8,008,278",100%,"8,242,624",100%,"8,550,971",100%,"8,821,027",100%,"9,025,145",100%
1,Total Population,Bronx,"1,451,277",18.39%,"1,424,815",18.31%,"1,471,701",18.64%,"1,168,972",16.53%,...,"1,332,650",16.64%,"1,385,108",16.8%,"1,446,788",16.92%,"1,518,998",17.22%,"1,579,245",17.5%
2,Total Population,Brooklyn,"2,738,175",34.7%,"2,627,319",33.76%,"2,602,012",32.96%,"2,230,936",31.55%,...,"2,465,326",30.78%,"2,552,911",30.97%,"2,648,452",30.97%,"2,754,009",31.22%,"2,840,525",31.47%
3,Total Population,Manhattan,"1,960,101",24.84%,"1,698,281",21.82%,"1,539,233",19.5%,"1,428,285",20.2%,...,"1,537,195",19.2%,"1,585,873",19.24%,"1,638,281",19.16%,"1,676,720",19.01%,"1,691,617",18.74%
4,Total Population,Queens,"1,550,849",19.65%,"1,809,578",23.25%,"1,986,473",25.16%,"1,891,325",26.75%,...,"2,229,379",27.84%,"2,250,002",27.3%,"2,330,295",27.25%,"2,373,551",26.91%,"2,412,649",26.73%

In [10]:
#Drop unncessary columns of the population dataset
dropColPop = total_pop.copy()
dropColPop.drop(['Age Group','1950 - Boro share of NYC total','1960 - Boro share of NYC total',
                 '1970 - Boro share of NYC total','1980 - Boro share of NYC total',
                 '1990 - Boro share of NYC total','2000 - Boro share of NYC total',
                 '2010 - Boro share of NYC total','2020 - Boro share of NYC total',
                 '2030 - Boro share of NYC total','2040 - Boro share of NYC total'], axis=1, inplace=True)
dropColPop

,Borough,1950,1960,1970,1980,1990,2000,2010,2020,2030,2040
0,NYC Total,"7,891,957","7,781,984","7,894,862","7,071,639","7,322,564","8,008,278","8,242,624","8,550,971","8,821,027","9,025,145"
1,Bronx,"1,451,277","1,424,815","1,471,701","1,168,972","1,203,789","1,332,650","1,385,108","1,446,788","1,518,998","1,579,245"
2,Brooklyn,"2,738,175","2,627,319","2,602,012","2,230,936","2,300,664","2,465,326","2,552,911","2,648,452","2,754,009","2,840,525"
3,Manhattan,"1,960,101","1,698,281","1,539,233","1,428,285","1,487,536","1,537,195","1,585,873","1,638,281","1,676,720","1,691,617"
4,Queens,"1,550,849","1,809,578","1,986,473","1,891,325","1,951,598","2,229,379","2,250,002","2,330,295","2,373,551","2,412,649"
5,Staten Island,"191,555","221,991","295,443","352,121","378,977","443,728","468,730","487,155","497,749","501,109"