In [1]:
###------NYC HISTORIC DATA CRIME : DATA CLEANING-----###

In [2]:
# Data exploration
import pandas as pd

# Numerical
import numpy as np

import os
print(os.listdir('../'))

['.git', '.gitignore', 'Apriori Association', 'Data', 'LICENSE', 'Python Notebook']

In [3]:
## Read CSV
crimes_original = pd.read_csv('../Data/NYPD_Complaint_Data_Historic.csv', low_memory=False)
crimes_original.head()

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
0,101109527,12/31/2015,23:45:00,NaN,NaN,12/31/2015,113,FORGERY,729.0,"FORGERY,ETC.,UNCLASSIFIED-FELO",...,44.0,INSIDE,BAR/NIGHT CLUB,NaN,NaN,1007314.0,241257.0,40.828848,-73.916661,"(40.828848333, -73.916661142)"
1,153401121,12/31/2015,23:36:00,NaN,NaN,12/31/2015,101,MURDER & NON-NEGL. MANSLAUGHTER,NaN,NaN,...,103.0,OUTSIDE,NaN,NaN,NaN,1043991.0,193406.0,40.697338,-73.784557,"(40.697338138, -73.784556739)"
2,569369778,12/31/2015,23:30:00,NaN,NaN,12/31/2015,117,DANGEROUS DRUGS,503.0,"CONTROLLED SUBSTANCE,INTENT TO",...,28.0,NaN,OTHER,NaN,NaN,999463.0,231690.0,40.802607,-73.945052,"(40.802606608, -73.945051911)"
3,968417082,12/31/2015,23:30:00,NaN,NaN,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,105.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,1060183.0,177862.0,40.654549,-73.726339,"(40.654549444, -73.726338791)"
4,641637920,12/31/2015,23:25:00,12/31/2015,23:30:00,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,13.0,FRONT OF,OTHER,NaN,NaN,987606.0,208148.0,40.738002,-73.987891,"(40.7380024, -73.98789129)"

In [4]:
## Rows, column count
crimes_original.shape

(6048796, 24)

In [5]:
crimes_original.describe(include = [np.number])

,CMPLNT_NUM,KY_CD,PD_CD,ADDR_PCT_CD,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
count,6.048796e+06,6.048796e+06,6.043597e+06,6.048406e+06,5.842919e+06,5.842919e+06,5.842919e+06,5.842919e+06
mean,5.499503e+08,2.943302e+02,4.168017e+02,6.338767e+01,1.004664e+06,2.069676e+05,4.073471e+01,-7.392631e+01
std,2.597854e+08,1.488905e+02,2.181964e+02,3.444525e+01,2.144654e+04,3.048365e+04,8.367338e-02,7.734389e-02
min,1.000002e+08,1.010000e+02,1.010000e+02,1.000000e+00,9.133190e+05,1.208290e+05,4.049806e+01,-7.425508e+01
25%,3.249627e+08,1.170000e+02,2.540000e+02,4.000000e+01,9.917040e+05,1.841860e+05,4.067215e+01,-7.397312e+01
50%,5.499772e+08,3.410000e+02,3.890000e+02,6.300000e+01,1.004299e+06,2.057360e+05,4.073135e+01,-7.392764e+01
75%,7.748521e+08,3.510000e+02,6.370000e+02,9.400000e+01,1.016295e+06,2.351880e+05,4.081219e+01,-7.388423e+01
max,9.999999e+08,8.810000e+02,9.750000e+02,1.230000e+02,1.067298e+06,2.718200e+05,4.091272e+01,-7.370032e+01

In [6]:
crimes_original.describe(include = [np.object])

,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,OFNS_DESC,PD_DESC,CRM_ATPT_CPTD_CD,LAW_CAT_CD,JURIS_DESC,BORO_NM,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,Lat_Lon
count,6048141,6048748,4502894,4506996,6048796,6029882,6043597,6048789,6048796,6048796,6048333,4734744,6011783,16608,302062,5842919
unique,7258,1442,5610,1441,4383,70,413,2,3,25,5,6,70,1066,279,114696
top,01/01/2010,12:00:00,10/17/2014,12:00:00,05/29/2007,PETIT LARCENY,ASSAULT 3,COMPLETED,MISDEMEANOR,N.Y. POLICE DEPT,BROOKLYN,INSIDE,STREET,CENTRAL PARK,CASTLE HILL,"(40.750430768, -73.989282176)"
freq,2395,161307,1369,79548,1903,987326,522223,5944652,3439409,5373664,1804644,3026995,1978203,1056,6673,19442

In [7]:
crime_remCol = crimes_original.drop(['KY_CD','JURIS_DESC','ADDR_PCT_CD','PD_CD','PARKS_NM','HADEVELOPT','X_COORD_CD','Y_COORD_CD'], axis=1)
print(crime_remCol)

         CMPLNT_NUM CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM  \
0         101109527   12/31/2015     23:45:00          NaN          NaN
1         153401121   12/31/2015     23:36:00          NaN          NaN
2         569369778   12/31/2015     23:30:00          NaN          NaN
3         968417082   12/31/2015     23:30:00          NaN          NaN
4         641637920   12/31/2015     23:25:00   12/31/2015     23:30:00
5         365661343   12/31/2015     23:18:00   12/31/2015     23:25:00
6         608231454   12/31/2015     23:15:00          NaN          NaN
7         265023856   12/31/2015     23:15:00   12/31/2015     23:15:00
8         989238731   12/31/2015     23:15:00   12/31/2015     23:30:00
9         415095955   12/31/2015     23:10:00   12/31/2015     23:10:00
10        731283092   12/31/2015     23:05:00   12/31/2015     23:15:00
11        178090167   12/31/2015     23:00:00   12/31/2015     23:05:00
12        898496564   12/31/2015     23:00:00          NaN          NaN
13        566081066   12/31/2015     23:00:00          NaN          NaN
14        584555879   12/31/2015     23:00:00          NaN          NaN
15        715942154   12/31/2015     23:00:00   12/31/2015     23:05:00
16        338440707   12/31/2015     23:00:00   12/31/2015     23:10:00
17        433257334   12/31/2015     23:00:00   12/31/2015     23:05:00
18        761004485   12/31/2015     23:00:00   12/31/2015     23:05:00
19        234892198   12/31/2015     22:55:00   12/31/2015     23:10:00
20        231688534   12/31/2015     22:53:00   12/31/2015     22:55:00
21        340513307   04/06/2015     12:00:00   04/10/2015     18:00:00
22        704037588   12/31/2015     22:50:00   12/31/2015     22:57:00
23        549465293   12/31/2015     22:50:00   12/31/2015     22:58:00
24        693907266   12/31/2015     22:45:00   12/31/2015     22:50:00
25        371600116   12/31/2015     22:45:00   12/31/2015     22:50:00
26        359273994   12/31/2015     22:45:00   12/31/2015     22:55:00
27        415805453   12/31/2015     22:45:00          NaN          NaN
28        251546004   12/31/2015     22:40:00   12/31/2015     22:50:00
29        624630216   12/31/2015     22:40:00   12/31/2015     22:56:00
...             ...          ...          ...          ...          ...
6048766   257531441   12/16/2016     15:25:00   12/16/2016     15:30:00
6048767   924787396   12/15/2016     22:01:00   12/15/2016     22:03:00
6048768   626569375   12/10/2016     19:00:00   12/11/2016     12:00:00
6048769   514844467   12/10/2016     14:00:00   12/10/2016     15:00:00
6048770   376183862   12/09/2016     01:00:00   12/14/2016     22:00:00
6048771   419208730   12/05/2016     23:00:00   12/05/2016     23:10:00
6048772   564382220   12/04/2016     20:00:00   12/06/2016     08:00:00
6048773   421318231   12/03/2016     16:00:00   01/01/2017     10:00:00
6048774   736943522   12/03/2016     15:00:00   12/20/2016     15:00:00
6048775   264440192   12/03/2016     03:30:00   12/03/2016     03:40:00
6048776   832707021   12/01/2016     16:00:00   01/08/2017     11:50:00
6048777   781849083   11/30/2016     21:00:00   11/30/2016     21:15:00
6048778   564963325   11/16/2016     00:30:00   11/16/2016     01:00:00
6048779   120230345   10/27/2016     00:01:00   10/27/2016     23:00:00
6048780   227833735   10/21/2016     13:00:00   10/21/2016     13:15:00
6048781   548130183   10/13/2016     01:30:00   10/13/2016     02:00:00
6048782   693530867   10/12/2016     10:00:00          NaN          NaN
6048783   637293210   10/05/2016     00:00:00   01/01/2017     21:16:00
6048784   766452024   10/04/2016     09:00:00   10/04/2016     09:30:00
6048785   486460516   07/01/2016     00:01:00   01/01/2017     16:40:00
6048786   977298651   05/29/2016     12:29:00          NaN          NaN
6048787   243551498   04/01/2016     00:00:00   06/01/2016     23:59:00
6048788   181622017   03/01/2016     13:00:00   01/01/2017     22:30:00
6048789   626739714   01/01/2016     06:10:00   01/01/2017     06:12:00
6048790   492890715   01/01/2016     06:00:00   01/01/2017     06:15:00
6048791   657605513   01/01/2016     04:00:00   01/01/2016     04:10:00
6048792   553117159   01/01/2016     03:00:00   01/01/2017     07:00:00
6048793   473961688   12/01/2015     00:00:00   12/01/2015     00:00:00
6048794   479719874   07/01/2015     18:05:00   07/01/2015     18:15:00
6048795   329336049   10/01/2012     00:01:00   10/01/2012     00:01:00

             RPT_DT                        OFNS_DESC  \
0        12/31/2015                          FORGERY
1        12/31/2015  MURDER & NON-NEGL. MANSLAUGHTER
2        12/31/2015                  DANGEROUS DRUGS
3        12/31/2015     ASSAULT 3 & RELATED OFFENSES
4        12/31/2015     ASSAULT 3 & RELATED OFFENSES
5        12/31/2015                   FELONY ASSAULT
6        12/31/2015                  DANGEROUS DRUGS
7        12/31/2015                DANGEROUS WEAPONS
8        12/31/2015     ASSAULT 3 & RELATED OFFENSES
9        12/31/2015                    PETIT LARCENY
10       12/31/2015                    PETIT LARCENY
11       12/31/2015                    PETIT LARCENY
12       12/31/2015                    GRAND LARCENY
13       12/31/2015                    GRAND LARCENY
14       12/31/2015                          FORGERY
15       12/31/2015                          ROBBERY
16       12/31/2015                    GRAND LARCENY
17       12/31/2015   OFFENSES AGAINST PUBLIC ADMINI
18       12/31/2015     ASSAULT 3 & RELATED OFFENSES
19       12/31/2015   CRIMINAL MISCHIEF & RELATED OF
20       12/31/2015                  DANGEROUS DRUGS
21       12/21/2015                             RAPE
22       12/31/2015                  DANGEROUS DRUGS
23       12/31/2015                   FELONY ASSAULT
24       12/31/2015                DANGEROUS WEAPONS
25       12/31/2015     ASSAULT 3 & RELATED OFFENSES
26       12/31/2015     ASSAULT 3 & RELATED OFFENSES
27       12/31/2015                DANGEROUS WEAPONS
28       12/31/2015                  DANGEROUS DRUGS
29       12/31/2015   INTOXICATED & IMPAIRED DRIVING
...             ...                              ...
6048766  01/01/2017     ASSAULT 3 & RELATED OFFENSES
6048767  01/01/2017                    PETIT LARCENY
6048768  01/01/2017   CRIMINAL MISCHIEF & RELATED OF
6048769  01/01/2017                      THEFT-FRAUD
6048770  01/01/2017   CRIMINAL MISCHIEF & RELATED OF
6048771  01/01/2017                   FELONY ASSAULT
6048772  01/01/2017   CRIMINAL MISCHIEF & RELATED OF
6048773  01/01/2017                    PETIT LARCENY
6048774  01/01/2017                    GRAND LARCENY
6048775  01/01/2017                    HARRASSMENT 2
6048776  01/01/2017                    PETIT LARCENY
6048777  01/01/2017          MISCELLANEOUS PENAL LAW
6048778  01/01/2017   CRIMINAL MISCHIEF & RELATED OF
6048779  01/01/2017                    PETIT LARCENY
6048780  01/01/2017                    HARRASSMENT 2
6048781  01/01/2017                   FELONY ASSAULT
6048782  01/01/2017                    PETIT LARCENY
6048783  01/01/2017                      THEFT-FRAUD
6048784  01/01/2017                    GRAND LARCENY
6048785  01/01/2017    OFF. AGNST PUB ORD SENSBLTY &
6048786  01/01/2017    OFF. AGNST PUB ORD SENSBLTY &
6048787  01/01/2017                       SEX CRIMES
6048788  01/01/2017                    HARRASSMENT 2
6048789  01/01/2017         VEHICLE AND TRAFFIC LAWS
6048790  01/01/2017                    PETIT LARCENY
6048791  01/01/2017   CRIMINAL MISCHIEF & RELATED OF
6048792  01/01/2017                    PETIT LARCENY
6048793  01/01/2017                      THEFT-FRAUD
6048794  01/01/2017     ASSAULT 3 & RELATED OFFENSES
6048795  01/01/2017                             RAPE

                                              PD_DESC CRM_ATPT_CPTD_CD  \
0                      FORGERY,ETC.,UNCLASSIFIED-FELO        COMPLETED
1                                                 NaN        COMPLETED
2                      CONTROLLED SUBSTANCE,INTENT TO        COMPLETED
3                                           ASSAULT 3        COMPLETED
4                                           ASSAULT 3        COMPLETED
5                            ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
6                      CONTROLLED SUBSTANCE, POSSESSI        COMPLETED
7                            WEAPONS POSSESSION 1 & 2        COMPLETED
8                                           ASSAULT 3        COMPLETED
9                      LARCENY,PETIT FROM BUILDING,UN        COMPLETED
10                           LARCENY,PETIT OF BICYCLE        COMPLETED
11                     LARCENY,PETIT FROM BUILDING,UN        COMPLETED
12            LARCENY,GRAND FROM PERSON, BAG OPEN/DIP        COMPLETED
13                     LARCENY,GRAND FROM PERSON,PICK        COMPLETED
14                     FORGERY,ETC.,UNCLASSIFIED-FELO        COMPLETED
15                 ROBBERY,PERSONAL ELECTRONIC DEVICE        COMPLETED
16              LARCENY,GRAND FROM EATERY, UNATTENDED        COMPLETED
17                                  CONTEMPT,CRIMINAL        COMPLETED
18                                          ASSAULT 3        COMPLETED
19                   CRIMINAL MISCHIEF,UNCLASSIFIED 4        COMPLETED
20                     CONTROLLED SUBSTANCE, POSSESSI        COMPLETED
21                                             RAPE 2        COMPLETED
22                     CONTROLLED SUBSTANCE, POSSESSI        COMPLETED
23                                  STRANGULATION 1ST        COMPLETED
24                               WEAPONS POSSESSION 3        COMPLETED
25                                          ASSAULT 3        COMPLETED
26                                          ASSAULT 3        COMPLETED
27                               WEAPONS POSSESSION 3        COMPLETED
28                        MARIJUANA, POSSESSION 4 & 5        COMPLETED
29                        INTOXICATED DRIVING,ALCOHOL        COMPLETED
...                                               ...              ...
6048766                                     ASSAULT 3        COMPLETED
6048767                LARCENY,PETIT FROM OPEN AREAS,        COMPLETED
6048768                MISCHIEF, CRIMINAL 4, OF MOTOR        COMPLETED
6048769                     FRAUD,UNCLASSIFIED-FELONY        COMPLETED
6048770                CRIMINAL MISCHIEF 4TH, GRAFFIT        COMPLETED
6048771                      ASSAULT 2,1,UNCLASSIFIED        COMPLETED
6048772                CRIMINAL MISCHIEF 4TH, GRAFFIT        COMPLETED
6048773                       LARCENY,PETIT FROM AUTO        COMPLETED
6048774  LARCENY,GRAND BY OPEN CREDIT CARD (NEW ACCT)        COMPLETED
6048775                         HARASSMENT,SUBD 3,4,5        COMPLETED
6048776                LARCENY,PETIT FROM OPEN AREAS,        COMPLETED
6048777                     TRESPASS 4,CRIMINAL SUB 2        COMPLETED
6048778              CRIMINAL MISCHIEF,UNCLASSIFIED 4        COMPLETED
6048779                LARCENY,PETIT FROM OPEN AREAS,        COMPLETED
6048780                    HARASSMENT,SUBD 1,CIVILIAN        COMPLETED
6048781                      ASSAULT 2,1,UNCLASSIFIED        COMPLETED
6048782                LARCENY,PETIT FROM BUILDING,UN        COMPLETED
6048783                     FRAUD,UNCLASSIFIED-FELONY        COMPLETED
6048784  LARCENY,GRAND BY IDENTITY THEFT-UNCLASSIFIED        COMPLETED
6048785                       AGGRAVATED HARASSMENT 2        COMPLETED
6048786                       AGGRAVATED HARASSMENT 2        COMPLETED
6048787                                  SEXUAL ABUSE        COMPLETED
6048788                         HARASSMENT,SUBD 3,4,5        COMPLETED
6048789                LEAVING SCENE-ACCIDENT-PERSONA        COMPLETED
6048790                LARCENY,PETIT BY FALSE PROMISE        COMPLETED
6048791              CRIMINAL MISCHIEF,UNCLASSIFIED 4        COMPLETED
6048792                LARCENY,PETIT FROM BUILDING,UN        COMPLETED
6048793                     FRAUD,UNCLASSIFIED-FELONY        COMPLETED
6048794                                     ASSAULT 3        COMPLETED
6048795                                        RAPE 3        COMPLETED

          LAW_CAT_CD        BORO_NM LOC_OF_OCCUR_DESC  \
0             FELONY          BRONX            INSIDE
1             FELONY         QUEENS           OUTSIDE
2             FELONY      MANHATTAN               NaN
3        MISDEMEANOR         QUEENS            INSIDE
4        MISDEMEANOR      MANHATTAN          FRONT OF
5             FELONY       BROOKLYN          FRONT OF
6        MISDEMEANOR      MANHATTAN       OPPOSITE OF
7             FELONY          BRONX          FRONT OF
8        MISDEMEANOR          BRONX            INSIDE
9        MISDEMEANOR      MANHATTAN            INSIDE
10       MISDEMEANOR          BRONX            INSIDE
11       MISDEMEANOR      MANHATTAN            INSIDE
12            FELONY      MANHATTAN               NaN
13            FELONY      MANHATTAN               NaN
14            FELONY       BROOKLYN               NaN
15            FELONY         QUEENS            INSIDE
16            FELONY      MANHATTAN            INSIDE
17       MISDEMEANOR          BRONX            INSIDE
18       MISDEMEANOR       BROOKLYN            INSIDE
19       MISDEMEANOR         QUEENS          FRONT OF
20       MISDEMEANOR       BROOKLYN               NaN
21            FELONY         QUEENS            INSIDE
22       MISDEMEANOR         QUEENS               NaN
23            FELONY       BROOKLYN            INSIDE
24            FELONY       BROOKLYN          FRONT OF
25       MISDEMEANOR       BROOKLYN          FRONT OF
26       MISDEMEANOR       BROOKLYN            INSIDE
27            FELONY       BROOKLYN               NaN
28       MISDEMEANOR       BROOKLYN            INSIDE
29       MISDEMEANOR  STATEN ISLAND               NaN
...              ...            ...               ...
6048766  MISDEMEANOR       BROOKLYN               NaN
6048767  MISDEMEANOR       BROOKLYN          FRONT OF
6048768  MISDEMEANOR       BROOKLYN          FRONT OF
6048769       FELONY          BRONX            INSIDE
6048770  MISDEMEANOR  STATEN ISLAND           REAR OF
6048771       FELONY       BROOKLYN            INSIDE
6048772  MISDEMEANOR  STATEN ISLAND           REAR OF
6048773  MISDEMEANOR          BRONX       OPPOSITE OF
6048774       FELONY         QUEENS            INSIDE
6048775    VIOLATION      MANHATTAN            INSIDE
6048776  MISDEMEANOR      MANHATTAN               NaN
6048777    VIOLATION       BROOKLYN            INSIDE
6048778  MISDEMEANOR          BRONX            INSIDE
6048779  MISDEMEANOR          BRONX            INSIDE
6048780    VIOLATION       BROOKLYN            INSIDE
6048781       FELONY       BROOKLYN            INSIDE
6048782  MISDEMEANOR      MANHATTAN            INSIDE
6048783       FELONY       BROOKLYN            INSIDE
6048784       FELONY       BROOKLYN            INSIDE
6048785  MISDEMEANOR       BROOKLYN            INSIDE
6048786  MISDEMEANOR       BROOKLYN            INSIDE
6048787       FELONY          BRONX            INSIDE
6048788    VIOLATION      MANHATTAN            INSIDE
6048789  MISDEMEANOR          BRONX               NaN
6048790  MISDEMEANOR       BROOKLYN               NaN
6048791  MISDEMEANOR         QUEENS          FRONT OF
6048792  MISDEMEANOR       BROOKLYN            INSIDE
6048793       FELONY          BRONX            INSIDE
6048794  MISDEMEANOR       BROOKLYN          FRONT OF
6048795       FELONY      MANHATTAN            INSIDE

                      PREM_TYP_DESC   Latitude  Longitude  \
0                    BAR/NIGHT CLUB  40.828848 -73.916661
1                               NaN  40.697338 -73.784557
2                             OTHER  40.802607 -73.945052
3                   RESIDENCE-HOUSE  40.654549 -73.726339
4                             OTHER  40.738002 -73.987891
5                        DRUG STORE  40.665023 -73.957111
6                            STREET  40.720200 -73.988735
7                            STREET  40.845707 -73.910398
8            RESIDENCE - APT. HOUSE  40.856711 -73.891900
9                        DRUG STORE  40.765618 -73.963623
10                        FAST FOOD  40.822040 -73.891732
11                 RESTAURANT/DINER  40.732828 -73.986063
12                           STREET  40.757916 -73.989299
13                           STREET  40.757916 -73.989299
14                           STREET  40.644562 -73.927662
15                   BAR/NIGHT CLUB  40.708096 -73.782102
16                 RESTAURANT/DINER  40.755197 -73.968296
17           RESIDENCE - APT. HOUSE  40.857924 -73.891952
18           RESIDENCE - APT. HOUSE  40.606309 -73.965133
19              DRY CLEANER/LAUNDRY  40.679499 -73.862825
20                           STREET  40.655642 -73.959863
21                            OTHER        NaN        NaN
22                           STREET  40.749307 -73.897578
23           RESIDENCE - APT. HOUSE  40.671237 -73.877222
24                  PUBLIC BUILDING  40.660258 -73.913671
25                 RESTAURANT/DINER  40.586060 -73.971743
26                  RESIDENCE-HOUSE  40.633033 -74.021193
27                           STREET  40.669800 -73.892398
28       RESIDENCE - PUBLIC HOUSING  40.696494 -73.949431
29                           STREET  40.624475 -74.158203
...                             ...        ...        ...
6048766            RESTAURANT/DINER  40.658928 -73.889820
6048767             RESIDENCE-HOUSE  40.609081 -73.950765
6048768                      STREET  40.625238 -73.918879
6048769             RESIDENCE-HOUSE  40.875384 -73.876043
6048770            RESTAURANT/DINER  40.626858 -74.163443
6048771             RESIDENCE-HOUSE  40.615745 -73.899206
6048772                 CHAIN STORE  40.623227 -74.149227
6048773                      STREET  40.877554 -73.872939
6048774             RESIDENCE-HOUSE  40.712419 -73.851024
6048775      RESIDENCE - APT. HOUSE  40.762273 -73.958568
6048776        TRANSIT - NYC SUBWAY  40.707763 -74.011706
6048777             RESIDENCE-HOUSE  40.633319 -73.968041
6048778      RESIDENCE - APT. HOUSE  40.853998 -73.827597
6048779      RESIDENCE - APT. HOUSE  40.890963 -73.832944
6048780                       OTHER  40.610198 -73.973260
6048781             RESIDENCE-HOUSE  40.667367 -73.903381
6048782                 CHAIN STORE  40.726738 -73.991602
6048783      RESIDENCE - APT. HOUSE  40.615460 -73.977943
6048784      OTHER HOUSE OF WORSHIP  40.663630 -73.955529
6048785  RESIDENCE - PUBLIC HOUSING  40.701646 -73.938012
6048786             RESIDENCE-HOUSE  40.666627 -73.886888
6048787  RESIDENCE - PUBLIC HOUSING        NaN        NaN
6048788      RESIDENCE - APT. HOUSE  40.781825 -73.947319
6048789                      STREET  40.848123 -73.901467
6048790                      STREET  40.670895 -73.936491
6048791                      STREET  40.676447 -73.804136
6048792              BAR/NIGHT CLUB  40.722142 -73.958701
6048793             RESIDENCE-HOUSE  40.890075 -73.855834
6048794              SMALL MERCHANT  40.613704 -73.981593
6048795  RESIDENCE - PUBLIC HOUSING        NaN        NaN

                               Lat_Lon
0        (40.828848333, -73.916661142)
1        (40.697338138, -73.784556739)
2        (40.802606608, -73.945051911)
3        (40.654549444, -73.726338791)
4           (40.7380024, -73.98789129)
5        (40.665022689, -73.957110763)
6        (40.720199996, -73.988735082)
7        (40.845707148, -73.910398033)
8        (40.856711291, -73.891899956)
9         (40.765617688, -73.96362342)
10       (40.822039935, -73.891732267)
11       (40.732828332, -73.986062857)
12        (40.757915693, -73.98929902)
13        (40.757915693, -73.98929902)
14        (40.644562053, -73.92766205)
15        (40.708095777, -73.78210174)
16       (40.755197275, -73.968296117)
17        (40.857924499, -73.89195221)
18       (40.606308897, -73.965132766)
19       (40.679498977, -73.862825258)
20       (40.655642023, -73.959863084)

In [8]:
# Fill CMPLNT_TO_DT NaNs with CMPLNT_FR_DT values.
crime_remCol['CMPLNT_TO_DT'].fillna(crime_remCol['CMPLNT_FR_DT'], axis = 0, inplace = True)
crime_remCol['CMPLNT_FR_DT'].fillna(crime_remCol['CMPLNT_TO_DT'], axis = 0, inplace = True)

# Fill CMPLNT_TO_TM NaNs with CMPLNT_FR_TM values.
crime_remCol['CMPLNT_TO_TM'].fillna(crime_remCol['CMPLNT_FR_TM'], axis = 0, inplace = True)
crime_remCol['CMPLNT_FR_TM'].fillna(crime_remCol['CMPLNT_TO_TM'], axis = 0, inplace = True)

In [9]:
# All NaNs from 'PD_DESC' series are filled with copy of 'OFNS_DESC' values
crime_remCol['OFNS_DESC'] = np.where(crime_remCol['OFNS_DESC'].isnull(), crime_remCol['PD_DESC'], crime_remCol['OFNS_DESC']) # There is pandas equivalent of np.where -> https://stackoverflow.com/questions/38579532/pandas-equivalent-of-np-where
# And vice versa
crime_remCol['PD_DESC'] = np.where(crime_remCol['PD_DESC'].isnull(), crime_remCol['OFNS_DESC'], crime_remCol['PD_DESC'])

In [10]:
#Remove Nan for premises.
prem_typ_desc_copy = crime_remCol['PREM_TYP_DESC'].copy(deep = True)
prem_typ_desc_copy_rand = prem_typ_desc_copy.value_counts(normalize = True).sort_values(ascending = False)

# Fill PREM_TYP_DESC values NaN values with values from locations of other incidents.
crime_remCol['PREM_TYP_DESC'] = crime_remCol['PREM_TYP_DESC'].apply(lambda x: np.random.choice([x for x in crime_remCol.prem_typ_desc],
                          replace = True, p = prem_typ_desc_copy_rand ) if (x == np.nan) else x).astype(str)

In [11]:
#Fill the location of occurance desc with max count
crime_remCol['LOC_OF_OCCUR_DESC'].fillna(value ='INSIDE', axis = 0, inplace = True)

In [12]:
crime_filt1 = crime_remCol.dropna(subset=['CMPLNT_FR_DT', 'CMPLNT_TO_DT'],how = "all")
crime_filt2 = crime_filt1.dropna(subset=['CMPLNT_FR_TM', 'CMPLNT_TO_TM'],how = "all")
crime_filt3 = crime_filt2.dropna(subset=['CRM_ATPT_CPTD_CD'],how = "all")
crime_filt4 = crime_filt3.dropna(subset=['BORO_NM'],how = "all")
crime_filt5 = crime_filt4.dropna(subset=['Latitude','Longitude','Lat_Lon'],how = "all")
#cleanedData = crime_filt5.copy()

In [14]:
crime_filt5.isnull().sum()

#To check the count of rows
#crime_filt5['LOC_OF_OCCUR_DESC'].value_counts(dropna=True)

CMPLNT_FR_DT         0
CMPLNT_FR_TM         0
CMPLNT_TO_DT         0
CMPLNT_TO_TM         0
RPT_DT               0
OFNS_DESC            0
PD_DESC              0
CRM_ATPT_CPTD_CD     0
LAW_CAT_CD           0
BORO_NM              0
LOC_OF_OCCUR_DESC    0
PREM_TYP_DESC        0
Latitude             0
Longitude            0
Lat_Lon              0
dtype: int64

In [13]:
data = crime_filt5.iloc[:,0:14].values
cleanedData = pd.DataFrame(data)